version: 1.0.{build}
configuration: Release
init:
- appveyor version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.0.0.{build}'
  assembly_file_version: '1.0.0.{build}'
before_build:
- ps: >-
    (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/4/6/1/46116DFF-29F9-4FF8-94BF-F9BE05BE263B/packages/DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe','core.exe')

    core.exe /install /quiet /norestart

    dotnet restore

    cd build
    npm install
    node appveyor-project-version-patch.js
    cd..

build:
  verbosity: minimal
build_script:
- cmd: >-
    dotnet pack src\twee.thetvdbapi --configuration Release --output "artifacts\bin\twee.thetvdbapi"
test_script:
- cmd: dotnet test .\test\twee.thetvdbapi.test
artifacts:
- path: artifacts\bin\twee.thetvdbapi\**\*.nupkg