version: v1.0.0.{build}
os: Visual Studio 2017

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/8cf3160c9516ef1f4effc825c0a44acc918a0b5a/appveyor-build-info.ps'))
  
install:
# Use the install script to grab the latest dotnet install
- ps: iex .\dotnet-latest.ps1

# Prepend newly installed dotnet cli to the PATH of this build (this cannot be
# done from inside the powershell script as it would require to restart
# the parent CMD process).
- "SET PATH=C:\\Program Files\\dotnet\\bin;%PATH%"

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.0.0.{build}'
  assembly_file_version: '1.0.0.{build}'

before_build:
- cmd: >-
    dotnet restore src\twee.thetvdbapi
    
    dotnet restore test\twee.thetvdbapi.test
    
    cd build
    
    npm install
    
    node appveyor-project-version-patch.js
    
    cd..
    

build_script:
- cmd: >-
    dotnet pack src\twee.thetvdbapi --configuration Release --output "artifacts\bin\twee.thetvdbapi"
test_script:
- cmd: dotnet test .\test\twee.thetvdbapi.test
artifacts:
- path: artifacts\bin\twee.thetvdbapi\**\*.nupkg
deploy:
 - provider: NuGet
   server: https://www.nuget.org/api/v2/package
   symbol_server: https://nuget.smbsrc.net
   api_key:
     secure: Z/RQ2kbKIKLj85f0uNyqqFNu2kQUJwsWppvhLGVxgcRHRMqLDdoKRueHIyFwjCt4
   artifact: /.*\.nupkg/
   on:
     branch: master